local translatedModes = {
	["play_casual"] = "CASUAL MODE",
	["play_insane"] = "INSANE MODE",
	["play_normal"] = "NORMAL MODE",
}

function init(self)
	
end

function update(self, dt)

end

function on_message(self, message_id, message, sender)
	print(message_id)
	
	if message_id == hash("set_mode") then
		local subtitle_node = gui.get_node("subtitle")

		gui.set_text( subtitle_node , "YOU'VE SUCCESSFULLY BEATEN\n" .. translatedModes[ message.mode ])
	end
end